# Configurations
title:            Quiz Template
longtitle:        Web Quiz setup
author:           Rajarshi Tiwari
email:            rajarshi.tiwari@ichec.ie
description: Generating quizzes for learning

url:              'https://rajarshitiwari.github.io'
baseurl:          '/quiz-template'
theme: minima

markdown_ext: md


# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
# favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown

exclude:
  - _drafts
  - scratch
  - README.md

include:
  - assets/quizzes


collections:
  quizzes:
    output: true
    permalink: /quizzes/:name

destination:      ./_site
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jemoji
  - jekyll-youtube

titles_from_headings:
  enabled: false
